# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84cfbbcb6bc25ec80ba790401c1d011201469bb00a4135c2f3ec0a78a86cc8c57332fa7c8dd77653f5c6b79c2e13112e7d27f52af76f5ae2a8a5897b872ad95

test:
  secret_key_base: edbf90c695dad601e9c38623dcdd737cdff5dc1e061a0767aed26052869773df13e51872178e5ce84c0b205981951831530e00dd7adb908400a8a0aaea8960d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
